using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ProjectEulerSolutions
{
    public partial class Form1 : Form
    {
        private int MAX_DONE = 3;
        public Form1()
        {
            InitializeComponent();
            updateComboBox();
        }
        private void updateComboBox()
        {
            for (int i = 1; i <= MAX_DONE; i++)
            {
                SolutionOptionsComboBox.Items.Add(i.ToString());
            }
        }

        private void RunButton_Click(object sender, EventArgs e)
        {
            int value;
            int.TryParse(SolutionOptionsComboBox.Text, out value);
            switch (value)
            {
                case 1: Problem_001(); break;
                case 2: Problem_002(); break;
                case 3: Problem_003(); break;
                default: break;

            }
        }



        public void Problem_001()
        {
            QuestionTextBox.Text =
                "Is we list al the natural numbers below 10 that "
                + "are multiples of 3 or 5, we get 3, 5, 6, and "
                + "9. The sum of these multiples is 23. "
                + "\nFind the sum of all the multiples of 3 "
                + "or 5 below 1000";

            int answer = 0;
            for (int i = 3; i < 1000; i++)
            {
                if (i % 3 == 0 || i % 5 == 0)
                {
                    answer += i;
                }
            }

            AnswerTextBox.Text = answer.ToString();
        }

        public void Problem_002()
        {
            QuestionTextBox.Text =
                "Each new term in the Fibonacci Sequence is "
                + "generated by adding the previous two terms. By "
                + "starting with 1 and 2, the first 10 terms will "
                + "be \n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... "
                + "\nBy considering the terms in the Fibonacci "
                + "sequence whose values do not exceed four million, "
                + "find the sum of even-valued terms.";

            bool done = false;
            int sum = 0;
            int last = 1;
            int current = 1;

            while (!done)
            {
                if (current > 4000000)   // if > 4 million
                {
                    done = true;
                    continue;
                }
                if (current % 2 == 0)    // if even
                {
                    sum += current;
                }
                int temp = current;
                current = current + last;
                last = temp;
            }

            AnswerTextBox.Text = sum.ToString();

        }

        public void Problem_003()
        {
            QuestionTextBox.Text =
                "The prime factors of 13195 are 5, 7, 13, and 29."
                + "/nWhat is the largest prime factor of "
                + "600851475143?";

            long Value = 600851475143;
            List<long> Primes = new List<long>();
            long LargestPrime = 0;
            int count = 0;
            for(long i = 2; i < Value / 2; i++)
            {
                count++;
                if(count % 10000 == 0)
                {
                    Console.WriteLine(count / 10000);
                }
                bool isPrime = true;
                for(long j = 2; j < i; j++)
                {
                    if(i % j == 0)
                    {
                        isPrime = false;
                        break;
                    }
                    if(isPrime && Value % i == 0)
                    {
                        LargestPrime = i;
                    }
                }
            }







            
            AnswerTextBox.Text = LargestPrime.ToString();
        }
            
                

    }
}
